# Generated by Django 4.1.3 on 2023-07-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='Title',
        ),
    ]
